import { StyleSheet, Text, View, StatusBar, Image, ScrollView, FlatList } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: StatusBar.currentHeight,
    backgroundColor: "#F3F2EF",
  },
  logo: {
    width: 35,
    height: 35,
    resizeMode: "contain",
    marginRight: 10,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  headerText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#0A66C2",
  }, 
  connectionContainer: {
    flexDirection: "row",
    paddingVertical: 15,
    paddingHorizontal: 15,
    backgroundColor: "#fff",
    marginBottom: 8,
  },
  connection: {
    alignItems: "center",
    marginRight: 15,
    width: 80,
  },
  connectionImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#0A66C2",
    resizeMode: "cover",
  },
  connectionName: {
    marginTop: 5,
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    color: "#333",
    width: 75,
  },
  connectionTitle: {
    fontSize: 9,
    textAlign: "center",
    color: "#666",
    width: 75,
    marginTop: 2,
  },
  postContainer: {
    marginBottom: 8,
    backgroundColor: "#fff",
    paddingBottom: 10,
  },
  profileImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 10,
  },
  userName: {
    fontWeight: "600",
    fontSize: 15,
    color: "#000",
  },
  jobTitle: {
    fontSize: 12,
    color: "#666",
    marginTop: 2,
  },
  timePosted: {
    fontSize: 11,
    color: "#999",
    marginTop: 2,
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingTop: 12,
    marginBottom: 8,
  },
  userDetails: {
    flex: 1,
  },
  captionContainer: {
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  caption: {
    fontSize: 14,
    color: "#000",
    lineHeight: 20,
  },
  postImage: {
    width: "100%",
    height: 300,
    resizeMode: "cover",
  },
  engagementStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
  },
  statsText: {
    fontSize: 12,
    color: "#666",
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 15,
    paddingTop: 8,
  },
  actionButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
  },
  actionButtonText: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  containerLanding: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    width: "100%",
  },
  logoLanding: {
    width: 100,
    height: 100,
    marginBottom: 20,
    borderRadius: 20,
  },
  titleLanding: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 10,
  },
  subtitleLanding: {
    fontSize: 16,
    color: "white",
    paddingHorizontal: 20,
    marginBottom: 30,
    textAlign: "center",
  },
  buttonLanding: {
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 30,
    marginVertical: 10,
    width: "60%",
    alignItems: "center",
  },
  buttonTextLanding: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#0A66C2",
  },
  secondaryButtonLanding: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#fff",
  },
  secondaryButtonTextLanding: {
    color: "#fff",
    },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerProfileImage: {
    width: 34,
    height: 34,
    borderRadius: 17,
    marginRight: 12,
    marginLeft: 12
  },
  searchBarContainer: {
    flex: 1,
    backgroundColor: '#EEF3F8',
    height: 36,
    borderRadius: 40,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  searchText: {
    color: '#666',
    fontSize: 14,
    marginLeft: 8,
  },
  fab: {
  position: 'absolute',
  right: 20,
  bottom: 20,
  color: '#e0e0e0',
  backgroundColor: '#007AFF',
  width: 86,
  height: 86,
  borderRadius: 28,
  justifyContent: 'center',
  alignItems: 'center',
},
  AlertPopContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  AlertPopButton: {
    backgroundColor: '#007AFF',
    padding: 15,
    borderRadius: 8,
  },
  AlertPopButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  post_container: {
    flex: 1,
    backgroundColor: "#1b1f23",
  },
  post_header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: '#333',
  },
  post_headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  post_Button: {
    backgroundColor: '#0a66c2',
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 20,
  },
  post_ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  post_inputContainer: {
    flexDirection: 'row',
    padding: 15,
  },
  post_profilePic: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    marginRight: 15,
  },
  post_input: {
    flex: 1,
    color: '#fff',
    fontSize: 18,
    textAlignVertical: 'top',
    paddingTop: 10,
  },
})